gem 'sinatra'
gem 'httparty'
gem 'rackup', '~> 2.2'
gem 'puma', '~> 6.6'
gem 'sqlite3'
gem 'sinatra-activerecord'
gem 'rake'

gem 'forest_admin_rpc_agent', path: '/Users/matthieuvideaud/Sites/agents/in-app/agent-ruby/packages/forest_admin_rpc_agent'
gem 'forest_admin_agent', path: '/Users/matthieuvideaud/Sites/agents/in-app/agent-ruby/packages/forest_admin_agent'
gem 'forest_admin_datasource_customizer', path: '/Users/matthieuvideaud/Sites/agents/in-app/agent-ruby/packages/forest_admin_datasource_customizer'
gem 'forest_admin_datasource_toolkit', path: '/Users/matthieuvideaud/Sites/agents/in-app/agent-ruby/packages/forest_admin_datasource_toolkit'
